// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
	Isbn sql.NullInt64  `json:"isbn"`
}

type Book struct {
	Isbn          int64          `json:"isbn"`
	Title         sql.NullString `json:"title"`
	Description   sql.NullString `json:"description"`
	Publisher     sql.NullString `json:"publisher"`
	PublishedDate sql.NullString `json:"published_date"`
	Pages         sql.NullInt64  `json:"pages"`
	Language      sql.NullString `json:"language"`
	CoverUrl      sql.NullString `json:"cover_url"`
	ShelfID       sql.NullInt64  `json:"shelf_id"`
	RowNumber     sql.NullInt64  `json:"row_number"`
	IsAiEnriched  sql.NullInt64  `json:"is_ai_enriched"`
}

type Borrowing struct {
	ID         int64          `json:"id"`
	Isbn       int64          `json:"isbn"`
	PersonID   int64          `json:"person_id"`
	BorrowedAt string         `json:"borrowed_at"`
	ReturnedAt sql.NullString `json:"returned_at"`
}

type Category struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
	Isbn sql.NullInt64  `json:"isbn"`
}

type Person struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Shelf struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	RowsCount sql.NullInt64  `json:"rows_count"`
}
