// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountAuthors(ctx context.Context, isbn sql.NullInt64) (int64, error)
	CountCategories(ctx context.Context, isbn sql.NullInt64) (int64, error)
	DeleteBook(ctx context.Context, isbn int64) (int64, error)
	GetActiveBorrowings(ctx context.Context) ([]GetActiveBorrowingsRow, error)
	GetAllBooks(ctx context.Context) ([]GetAllBooksRow, error)
	GetAllPeople(ctx context.Context) ([]Person, error)
	GetAllShelfs(ctx context.Context) ([]Shelf, error)
	GetAuthors(ctx context.Context, isbn sql.NullInt64) ([]sql.NullString, error)
	GetBook(ctx context.Context, isbn int64) (GetBookRow, error)
	GetCategories(ctx context.Context, isbn sql.NullInt64) ([]sql.NullString, error)
	GetPerson(ctx context.Context, name string) (int64, error)
	GetShelf(ctx context.Context, id int64) (Shelf, error)
	GetShelfName(ctx context.Context, id int64) (sql.NullString, error)
	GetUnenrichedBooks(ctx context.Context) ([]int64, error)
	InsertAuthor(ctx context.Context, arg InsertAuthorParams) error
	InsertBook(ctx context.Context, arg InsertBookParams) error
	InsertBorrowing(ctx context.Context, arg InsertBorrowingParams) error
	InsertCategory(ctx context.Context, arg InsertCategoryParams) error
	InsertPerson(ctx context.Context, name string) (int64, error)
	InsertShelf(ctx context.Context, arg InsertShelfParams) error
	MarkBookAsEnriched(ctx context.Context, isbn int64) error
	ReturnBook(ctx context.Context, arg ReturnBookParams) error
	UpdateBookDescription(ctx context.Context, arg UpdateBookDescriptionParams) error
	UpdateBookPublishedDate(ctx context.Context, arg UpdateBookPublishedDateParams) error
	UpdateBookTitle(ctx context.Context, arg UpdateBookTitleParams) error
}

var _ Querier = (*Queries)(nil)
